import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import vm from 'node:vm';
test('backup warning only describes incomplete displayed fallback, not healthy Firebase reads', () => {
 const source = readFileSync(new URL('./CatContext.tsx', import.meta.url), 'utf8');
 const start = source.indexOf('const getCatBackupNotice');
 const end = source.indexOf('function CatBackupNotice', start);
 assert.ok(start >= 0);
 const context = {};
 vm.runInNewContext(ts.transpileModule(source.slice(start,end)+';globalThis.notice=getCatBackupNotice;', {compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);
 assert.equal(context.notice({mode:false,incomplete:true,pendingCount:0,error:null}),null);
 assert.match(context.notice({mode:true,incomplete:true,pendingCount:0,error:null}),/incomplete/);
 assert.match(context.notice({mode:true,incomplete:false,pendingCount:0,error:null}),/saved cat backup/);
 assert.match(context.notice({mode:false,incomplete:false,pendingCount:1,error:null}),/awaiting recovery/);
 assert.match(context.notice({mode:false,incomplete:false,pendingCount:0,error:'failed'}),/unavailable/);
 assert.match(context.notice({mode:false,incomplete:true,pendingCount:0,error:null,historyLoading:true}),/Loading visit history/);
 assert.match(context.notice({mode:true,incomplete:true,pendingCount:0,error:null,historyLoading:true}),/Loading visit history/);
 assert.match(context.notice({mode:false,incomplete:true,pendingCount:0,error:'failed',historyLoading:true}),/unavailable/);
});
