import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
import test from 'node:test';
import ts from 'typescript';

test('backup adapter scopes owners, hashes devices, validates inputs, preserves dates and handles void RPC', async () => {
  const calls = [];
  let result = null, status = 200, voidBody = false;
  const modules = {};
  function load(file) {
    const loaded = { exports: {} };
    vm.runInNewContext(ts.transpileModule(readFileSync(new URL(file, import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, { module: loaded, exports: loaded.exports, Date, Buffer, require: name => name === 'node:crypto' ? crypto : name === './catHistoryNormalization' ? modules.normalization : { smsStoreRequest: async (path, init) => {
      calls.push({ path, body: JSON.parse(init.body) });
      return { ok: status === 200, status, json: async () => { if (voidBody) throw new SyntaxError('Empty response'); return result; } };
    } } });
    return loaded.exports;
  }
  modules.normalization = load('./catHistoryNormalization.ts');
  const store = load('./catHistoryStore.ts');
  const catalog = { revision: 1, profiles: [{ catId: 'cat-a', cat: { name: 'Cat' }, details: { rfidTag: 'AABB' } }], sourceReadAt: new Date().toISOString(), complete: true };
  result = { applied: true };
  assert.equal((await store.saveCatalogBackup('owner-a', catalog)).applied, true);
  assert.equal(calls.pop().body.p_owner_id, 'owner-a');
  result = catalog;
  assert.equal((await store.readCatalogBackup('owner-b')).revision, 1);
  assert.equal(calls.pop().body.p_owner_id, 'owner-b');
  const visit = modules.normalization.buildVisitBackup('sync-event', { catId: 'cat-a', date: '2026-10-04', durationSecs: 32 }, null, 'primary_saved');
  result = { inserted: 1, duplicates: 0, conflicts: 0 };
  await store.saveVisitBackups('owner-a', [visit]);
  assert.equal(calls.pop().body.p_visits[0].data.date, '2026-10-04');
  result = { rows: [visit], nextCursor: 'opaque', source: 'supabase', complete: true, backedUpAt: catalog.sourceReadAt, pendingCount: 0 };
  assert.equal((await store.readVisitBackups('owner-a', { startDate: '2026-10-01', endDate: '2026-10-04', sort: 'desc', limit: 50 })).rows.length, 1);
  assert.equal(calls.pop().body.p_owner_id, 'owner-a');
  result = null;
  assert.equal(await store.resolveCatBackupDevice('cfg_abcdefghijklmnop'), null);
  const call = calls.pop();
  assert.equal(call.body.p_token_hash, crypto.createHash('sha256').update('cfg_abcdefghijklmnop').digest('hex'));
  assert.equal(JSON.stringify(call).includes('cfg_abcdefghijklmnop'), false);
  const progress = { cursor: null, scanned: 0, complete: false, checkedAt: catalog.sourceReadAt, lastError: null };
  voidBody = true;
  await store.saveBackupProgress('owner-a', progress);
  await store.finishClaim('12345678-1234-4234-8234-123456789abc', 'retry', 'Primary unavailable');
  await store.finishRepairOwner('12345678-1234-4234-8234-123456789abc', 'success');
  voidBody = false; result = [];
  await store.claimPendingVisits(5);
  assert.equal(calls.pop().body.p_limit, 5);
  const before = calls.length;
  await assert.rejects(store.readCatalogBackup(''));
  await assert.rejects(store.saveCatalogBackup('owner-a', { ...catalog, complete: false }));
  await assert.rejects(store.saveCatalogBackup('owner-a', { ...catalog, profiles: [...catalog.profiles, ...catalog.profiles] }));
  await assert.rejects(store.saveVisitBackups('owner-a', [{ ...visit, digest: '0'.repeat(64) }]));
  await assert.rejects(store.claimPendingVisits(6));
  await assert.rejects(store.readVisitBackups('owner-a', { startDate: 'bad', endDate: '2026-10-04', sort: 'desc', limit: 50 }));
  await assert.rejects(store.resolveCatBackupDevice('bad'));
  await assert.rejects(store.finishClaim('not-uuid', 'retry'));
  assert.equal(calls.length, before);
  status = 503;
  await assert.rejects(store.readCatalogBackup('owner-a'), /503/);
  await assert.rejects(store.saveBackupProgress('owner-a', progress), /503/);
});
